spring.profiles.active: @profiles.active@

---

spring.profiles: development

logging:
 file: /home/huoshan/log/authority_web.log
 level.root: DEBUG

spring.freemarker:
 cache: false
 charset: UTF-8
 enabled: true
 suffix: .ftl

server:
 port: 8083
 
authority.service.rest.baseurl: http://localhost:9000/api


cas.server:
 login.url: https://sso.localcodeblog.net
 logout.url: https://sso.localcodeblog.net/logout

platform.sign: AUTHORITY
authority.service.rest.url: http://localhost:9000/api
spring.security.logout.url: /j_spring_cas_security_logout
denied.page: /403

security.basic.enabled: false


---

spring.profiles: production


logging:
 file: /opt/logs/authority/web/authority_web.log
 level.root: WARN

spring.freemarker:
 cache: false
 charset: UTF-8
 enabled: true
 suffix: .ftl

server:
 port: 8000
 
authority.service.rest.baseurl: http://60.205.207.39:9000/api


cas.server:
 login.url: https://sso.codeblog.net
 logout.url: https://sso.codeblog.net/logout

platform.sign: AUTHORITY
authority.service.rest.url: http://60.205.207.39:9000/api
spring.security.logout.url: /j_spring_cas_security_logout
denied.page: /403

security.basic.enabled: false


