-- MySQL Script generated by MySQL Workbench
-- 2016年12月26日 星期一 15时45分15秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema authority
-- -----------------------------------------------------
-- 权限数据库

-- -----------------------------------------------------
-- Schema authority
--
-- 权限数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `authority` DEFAULT CHARACTER SET utf8 ;
USE `authority` ;

-- -----------------------------------------------------
-- Table `authority`.`authority_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authority`.`authority_user` ;

CREATE TABLE IF NOT EXISTS `authority`.`authority_user` (
  `user_uuid` VARCHAR(32) NOT NULL COMMENT '主键',
  `user_login_name` VARCHAR(64) NULL COMMENT '登录名\n由字母，数字，下划线组合',
  `user_login_pwd` VARCHAR(64) NOT NULL COMMENT '登陆密码',
  `user_email` VARCHAR(128) NOT NULL COMMENT '用户邮箱',
  `user_phone` VARCHAR(32) NULL COMMENT '用户电话',
  `user_status` INT NOT NULL COMMENT '用户状态:\n\n已注册未激活: 1\n已注册并激活:2\n已锁定:3\n',
  `user_add_time` VARCHAR(32) NOT NULL COMMENT '添加用户时间\nyyyy-MM-dd HH:mm:ss',
  `user_add_by` VARCHAR(32) NULL COMMENT '添加用户人(用户主键)',
  `user_del_time` VARCHAR(32) NULL COMMENT '删除用户时间\nyyyy-MM-dd HH:mm:ss\n',
  `user_del_by` VARCHAR(32) NULL COMMENT '删除用户人（用户主键）',
  `user_type` INT NOT NULL COMMENT '用户类型：\n\n内部用户:1\n外部用户：2\n',
  `user_add_type` INT NOT NULL COMMENT '添加用户类型:\n\n被内部用户添加：1\n\n自己注册:2',
  `user_is_delete` INT NOT NULL DEFAULT 0 COMMENT '是否已被删除:\n\n0：未\n1：已被删除',
  PRIMARY KEY (`user_uuid`),
  UNIQUE INDEX `user_uuid_UNIQUE` (`user_uuid` ASC),
  UNIQUE INDEX `user_login_name_UNIQUE` (`user_login_name` ASC),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC),
  UNIQUE INDEX `user_phone_UNIQUE` (`user_phone` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `authority`.`authority_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authority`.`authority_role` ;

CREATE TABLE IF NOT EXISTS `authority`.`authority_role` (
  `role_uuid` VARCHAR(32) NOT NULL COMMENT '主键',
  `role_name` VARCHAR(32) NOT NULL COMMENT '角色名称',
  `role_status` INT NOT NULL COMMENT '角色状态:\n\n已添加：\n已激活:\n',
  `role_add_time` VARCHAR(32) NOT NULL COMMENT '添加时间\nyyyy-MM-dd HH:mm:ss',
  `role_add_by` VARCHAR(32) NOT NULL COMMENT '添加人uuid',
  `role_del_time` VARCHAR(32) NULL COMMENT '删除时间\nyyyy-MM-dd HH:mm:ss',
  `role_del_by` VARCHAR(32) NULL COMMENT '删除人uuid',
  `role_is_delete` INT NOT NULL DEFAULT 0 COMMENT '是否已被删除:\n\n0:未\n1：已被删除',
  `role_platform_uuid` VARCHAR(32) NOT NULL COMMENT '平台uuid',
  PRIMARY KEY (`role_uuid`),
  UNIQUE INDEX `role_uuid_UNIQUE` (`role_uuid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `authority`.`authority_user_role_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authority`.`authority_user_role_relation` ;

CREATE TABLE IF NOT EXISTS `authority`.`authority_user_role_relation` (
  `ur_uuid` VARCHAR(32) NOT NULL COMMENT '主键',
  `ur_user_uuid` VARCHAR(32) NOT NULL COMMENT '用户uuid',
  `ur_role_uuid` VARCHAR(32) NOT NULL COMMENT '角色uuid',
  `ur_add_time` VARCHAR(32) NOT NULL COMMENT '增加时间\nyyyy-MM-dd HH:mm:ss',
  `ur_add_by` VARCHAR(32) NOT NULL COMMENT '增加人(用户主键)',
  `ur_del_time` VARCHAR(32) NULL COMMENT '删除时间\nyyyy-MM-dd HH:mm:ss',
  `ur_del_by` VARCHAR(32) NULL COMMENT '删除人(用户主键)',
  `ur_is_delete` INT NOT NULL COMMENT '是否已被删除\n未：0\n已删除:1',
  PRIMARY KEY (`ur_uuid`),
  UNIQUE INDEX `ur_uuid_UNIQUE` (`ur_uuid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '用户角色关联表';


-- -----------------------------------------------------
-- Table `authority`.`authority_resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authority`.`authority_resources` ;

CREATE TABLE IF NOT EXISTS `authority`.`authority_resources` (
  `resource_uuid` VARCHAR(32) NOT NULL COMMENT '主键',
  `resource_name` VARCHAR(45) NOT NULL COMMENT '资源名称',
  `resource_platform_uuid` VARCHAR(32) NOT NULL COMMENT '资源所在平台uuid',
  `resource_status` INT NOT NULL DEFAULT 0 COMMENT '资源状态:\n\n未激活：0\n已激活：1\n已注销：2',
  `resource_url` VARCHAR(128) NOT NULL COMMENT '资源链接',
  `resource_level` INT NOT NULL COMMENT '资源层级：\n资源分为: 1:系统 ，2:菜单3：菜单下资源。。。\n',
  `resource_order` INT NOT NULL COMMENT '资源在所在层级的序号编码',
  `resource_parent_uuid` VARCHAR(32) NOT NULL COMMENT '资源父级id',
  `resource_css_code` VARCHAR(45) NULL COMMENT '资源css code备用',
  `resource_add_time` VARCHAR(32) NOT NULL COMMENT '资源增加时间\nyyyy-MM-dd HH:mm:ss',
  `resource_add_by` VARCHAR(32) NOT NULL COMMENT '资源增加人uuid',
  `resource_del_time` VARCHAR(32) NULL COMMENT '删除时间\nyyyy-MM-dd HH:mm:ss',
  `resource_del_by` VARCHAR(32) NULL COMMENT '删除人uuid',
  `resource__is_delete` INT NOT NULL COMMENT '0:未\n1：已删除',
  PRIMARY KEY (`resource_uuid`),
  UNIQUE INDEX `resource_uuid_UNIQUE` (`resource_uuid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '资源表';


-- -----------------------------------------------------
-- Table `authority`.`authority_role_resources_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authority`.`authority_role_resources_relation` ;

CREATE TABLE IF NOT EXISTS `authority`.`authority_role_resources_relation` (
  `rr_role_uuid` VARCHAR(32) NOT NULL COMMENT '角色uuid',
  `rr_resource_uuid` VARCHAR(32) NOT NULL COMMENT '资源uuid',
  `rr_uuid` VARCHAR(32) NOT NULL COMMENT '主键',
  `rr_add_time` VARCHAR(32) NOT NULL COMMENT '添加时间\nyyyy-MM-dd HH:mm:ss',
  `rr_add_by` VARCHAR(32) NOT NULL COMMENT '添加人uuid',
  `rr_del_time` VARCHAR(32) NULL COMMENT '删除时间\nyyyy:mm:dd HH:mm:ss',
  `rr_del_by` VARCHAR(32) NULL COMMENT '删除人uuid',
  `rr_is_delete` INT NOT NULL DEFAULT 0 COMMENT '是否已被删除:\n\n0:未\n1：已被删除',
  `rr_grant_type` INT NOT NULL COMMENT '授予类型:  \n\n0： 读，写\n1： 读\n\n\n',
  PRIMARY KEY (`rr_uuid`),
  UNIQUE INDEX `rr_uuid_UNIQUE` (`rr_uuid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '角色资源关联表';


-- -----------------------------------------------------
-- Table `authority`.`platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authority`.`platform` ;

CREATE TABLE IF NOT EXISTS `authority`.`platform` (
  `platform_uuid` VARCHAR(32) NOT NULL COMMENT '主键',
  `platform_name` VARCHAR(50) NOT NULL COMMENT '平台名',
  `platform_sign` VARCHAR(32) NOT NULL COMMENT '平台标识',
  `platform_domain_name` VARCHAR(30) NOT NULL COMMENT '平台域名',
  `platform_add_time` VARCHAR(32) NOT NULL COMMENT '添加时间\nyyyy-MM-dd HH:mm:ss',
  `platform_add_by` VARCHAR(32) NOT NULL COMMENT '添加人uuid',
  `platform_del_time` VARCHAR(32) NULL COMMENT '删除时间\nyyyy-MM-dd HH:mm:ss',
  `platform_del_by` VARCHAR(32) NULL COMMENT '删除人uuid',
  `platform_status` INT NOT NULL COMMENT '平台状态：\n\n初始化: 0\n激活: 1\n注销: 2',
  `platform_is_delete` INT NOT NULL DEFAULT 0 COMMENT '是否已被删除:\n0：未\n1：已被删除',
  PRIMARY KEY (`platform_uuid`),
  UNIQUE INDEX `template_uuid_UNIQUE` (`platform_uuid` ASC),
  UNIQUE INDEX `template_sign_UNIQUE` (`platform_sign` ASC),
  UNIQUE INDEX `template_domain_name_UNIQUE` (`platform_domain_name` ASC))
ENGINE = InnoDB
COMMENT = '平台表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
