spring.datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/authority?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: llhua123
    max-active: 30
    
spring.jersey.type: servlet

mybatis:
    config-location: classpath:mybatis/sqlMapConfig.xml

logging:
    file: /home/huoshan/log/authority.log
    level.root: DEBUG
    
server:
    port: 9000
    
